language: node_js
node_js:
  - "10"
sudo: false
before_install:
  - openssl aes-256-cbc -K $encrypted_662eeefc1dcf_key -iv $encrypted_662eeefc1dcf_iv
    -in gcs-service-account.json.enc -out gcs-service-account.json
    -d
install:
  - yarn
  - npm install -g codecov
  - yarn global add @cognite/preview-cli@0.0.6
script:
  - yarn commitlint-travis
  - yarn lint
  - yarn build
  - yarn test && codecov
  - yarn build-storybook
  - |
    if [ "${TRAVIS_PULL_REQUEST}" != "false" ] ; then
      GOOGLE_APPLICATION_CREDENTIALS=gcs-service-account.json preview upload storybook-static "gearboxjs/pr-${TRAVIS_PULL_REQUEST}" && \
      curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST \
      -d "{\"body\": \"This PR's storybook can now be previewed at the following URL: https://pr-${TRAVIS_PULL_REQUEST}.gearboxjs.preview.cogniteapp.com\"}" \
      "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"
    fi
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: storybook-static
    on:
      branch: master
  - provider: script
    node_js: lts/*
    on:
      branch: master
    skip_cleanup: true
    script:
      - npx semantic-release

